disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "nojf1"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "The wonderful world of my uncontained thoughts on various subjects"
logo = "null"
secondaryLogo = "profile-photo.jpg"
copyright = "© { year } nojf1"

[params.author]
name = "Nicole"
image = "profile-photo.jpg"
imageQuality = 100
headline = "Software Engineering student at Wawasan Open University, currently looking for internship opportunities"
links = [
    {email = "mailto:ojfnicole@gmail.com"},
    {github = "https://github.com/nojf1"},
    {linkedin = "https://www.linkedin.com/in/nicole-jinn-faye-ooi-82b0282aa/"}
]